---
infra_config:
  - name: puppetdb.infra.test.rcarrillocruz.cloud
    image: 9d25fe2d-cf31-4b05-8c58-f238ec78e633
    flavor: standard.small
    net_name: infra-test-network
    infra_type: puppetdb
  - name: puppetmaster.infra.test.rcarrillocruz.cloud
    image: 9d25fe2d-cf31-4b05-8c58-f238ec78e633
    flavor: standard.small
    net_name: infra-test-network
    infra_type: puppetmaster
  - name: jenkins.infra.test.rcarrillocruz.cloud
    image: 9d25fe2d-cf31-4b05-8c58-f238ec78e633
    flavor: standard.small
    net_name: infra-test-network
    infra_type: jenkins
  - name: gerrit.infra.test.rcarrillocruz.cloud
    image: 9d25fe2d-cf31-4b05-8c58-f238ec78e633
    flavor: standard.small
    net_name: infra-test-network
    infra_type: gerrit
  - name: nodepool.infra.test.rcarrillocruz.cloud
    image: 9d25fe2d-cf31-4b05-8c58-f238ec78e633
    flavor: standard.small
    net_name: infra-test-network
    infra_type: nodepool
