---
- name: Create OpenStack instances
  os_server:
    state: present
    cloud: openstack
    name: "{{ item.name }}"
    region_name: region-b.geo-1
    availability_zone: az2
    image: "{{ item.image }}"
    key_name: workstation
    timeout: 200
    flavor: "{{ item.flavor }}"
    nics:
      - net-name: "{{ item.net_name }}"
    security_groups: default
    auto_floating_ip: yes
    meta: 
      group: infra
      infra_type: "{{ item.infra_type }}"
  with_items: infra_servers
