---
# Install puppetmaster packages
- apt: name={{ item }} state=installed
  with_items:
    - puppetmaster-passenger
    - hiera
    - hiera-puppet

# Puppet apply the puppetmaster manifest
- command: > 
    puppet apply --modulepath='/opt/git/system-config/modules:/etc/puppet/modules' 
    -e 'class {"openstack_project::puppetmaster"':' puppetdb_server => "{{ hostvars[groups['puppetdb'][0]]['openstack']['name'] }}" }'
