---
# Install puppetmaster packages
- apt: name={{ item }} state=installed
  with_items:
    - puppetmaster-passenger
    - hiera
    - hiera-puppet

# Puppet apply the puppetmaster manifest
- command: > 
    puppet apply --modulepath='/opt/system-config/production/modules:/etc/puppet/modules'
    -e 'class {"openstack_project::puppetmaster"':' puppetdb => false }'
  tags: puppet_apply
