---
# Download Jenkins CLI
- get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar dest=/tmp/jenkins-cli.jar
  register: result
  until: result|success
  retries: 5
  delay: 10

# Create JJB user
- shell: echo 'hpsr=new hudson.security.HudsonPrivateSecurityRealm(false); hpsr.createAccount("gerrig", "gerrig")' | java -jar /tmp/jenkins-cli.jar -s http://localhost:8080 groovy =
  no_log: True

# Trigger jenkins-jobs update in fire&forget mode, since it takes a long time to complete
- command: jenkins-jobs update /etc/jenkins_jobs/config --delete-old
  async: 3600
  poll: 0
