---
# Update packages
- apt: update_cache=yes

# Install git
- apt: name=git

# Clone system-config 
- git: repo=https://git.openstack.org/openstack-infra/system-config
       dest=/opt/system-config/production
  tags: clone_system_config

# Install puppet
- command: bash /opt/system-config/production/install_puppet.sh
  tags: install_puppet

# Install puppet modules
- command: bash /opt/system-config/production/install_modules.sh
  tags: install_puppet_modules
