---
# Clone system-config locally in the command machine
- git: repo="{{ system_config_repo_url }}"
       dest=/tmp/infra-ansible/system-config/production
       version="{{ system_config_branch }}"
       accept_hostkey=True
       force=True
  tags: clone_system_config_locally
